### ISSUE TITLE
Error: Could not find a production build in the '/Users/dmitriymalayev/Desktop/portfolio_website-STARTER/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

### ISSUE THREAD

**Issue by DmitriyMalayev** [adrianhajdin/portfolio_website#19]
dmitriymalayev@Dmitriys-Mini portfolio_website-STARTER % npm i    
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 306 packages, and audited 307 packages in 5s

45 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
dmitriymalayev@Dmitriys-Mini portfolio_website-STARTER % npm start

> portfolio_nextjs@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
Error: Could not find a production build in the '/Users/dmitriymalayev/Desktop/portfolio_website-STARTER/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at Server.readBuildId (/Users/dmitriymalayev/Desktop/portfolio_website-STARTER/node_modules/next/dist/next-server/server/next-server.js:151:355)
    at new Server (/Users/dmitriymalayev/Desktop/portfolio_website-STARTER/node_modules/next/dist/next-server/server/next-server.js:3:120)
    at NextServer.createServer (/Users/dmitriymalayev/Desktop/portfolio_website-STARTER/node_modules/next/dist/server/next.js:1:2935)
    at async /Users/dmitriymalayev/Desktop/portfolio_website-STARTER/node_modules/next/dist/server/next.js:1:3360
dmitriymalayev@Dmitriys-Mini portfolio_website-STARTER %

**Comment by ryanttang** [comment]
@DmitriyMalayev I had a similar problem and was able to get it to work by using version 16.13.0 of Node

> nvm install 16.13.0

**Comment by DmitriyMalayev** [comment]
Great, I will try. Thanks everyone.
Let's connect on LinkedIn


[image: photo-logo]
Dmitriy Malayev
Software Engineer

Mobile: 347-761-4403
E-Mail: ***@***.***

[image: linkedin] <https://img.newoldstamp.com/r/191948/linkedin> [image:
github] <https://img.newoldstamp.com/r/191948/github> [image: medium]
<https://img.newoldstamp.com/r/191948/medium> [image: youtube]
<https://img.newoldstamp.com/r/191948/youtube> [image: stackoverflow]
<https://img.newoldstamp.com/r/191948/stackoverflow>

[image: banner] <https://img.newoldstamp.com/r/191948/b>

**Comment by Omkarkale59** [comment]
i resolve this issue
simple u can just do it this simple steps

1. npm update latest
2. deleting the module and .next file
3. yarn
4. yarn dev

thnks for reading this
i take 2 days to understand this issue this is hectik for me to resolve this

**Comment by BogdaLD** [comment]
the same issue to me. and can't solove by update the node version.need help
