### ISSUE TITLE
issue on run

### ISSUE THREAD

**Issue by yagashiraevil** [adrianhajdin/portfolio_website#8]
> portfolio_nextjs@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Could not find a production build in the 'C:\Personal\portfolio_website\.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at Server.readBuildId (C:\Personal\portfolio_website\node_modules\next\dist\server\next-server.js:1559:23)
    at new Server (C:\Personal\portfolio_website\node_modules\next\dist\server\next-server.js:92:29)
    at NextServer.createServer (C:\Personal\portfolio_website\node_modules\next\dist\server\next.js:107:16)
    at async C:\Personal\portfolio_website\node_modules\next\dist\server\next.js:119:31

**Comment by raguilar27** [comment]
Try npm run dev

**Comment by yagashiraevil** [comment]
Worked thanks.
